criado inserir sessao pauta
GabbyVenturini/pauta pull request #14
Opened 2023-10-24 18:48 UTC by GabbyVenturini

2023-10-24 20:17 UTC, GuiRuchell commented on src/main/java/com/schedule/vote/controller/ScheduleController.java
> +    public Schedule insertSchedule(@RequestBody Schedule schedule){
essa parte de criar sessão ta bem redundante pra nós, vamos dar uma olhada em como melhorar isso :)

2023-10-24 20:18 UTC, GuiRuchell commented on src/main/java/com/schedule/vote/controller/ScheduleController.java
> +    @PostMapping("/insert")
o nome do endpoint pode ser /session

2023-10-24 20:19 UTC, GuiRuchell commented on schedule-vote.trace.db
>  org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-214]
se tu quiser usar um postgres da vida nessa api, não tem problema lembro que tu usava no projetinho da NT

2023-10-24 20:19 UTC, GuiRuchell commented on schedule-vote.trace.db
>  org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-214]
Mas o H2 é bem mais leve por ser em memória

2023-10-24 20:23 UTC, GabbyVenturini commented on src/main/java/com/schedule/vote/controller/ScheduleController.java
> +    @PostMapping("/insert")
está bem

2023-10-24 20:24 UTC, GabbyVenturini commented on src/main/java/com/schedule/vote/controller/ScheduleController.java
> +    @PostMapping("/insert")
fui pelo nome do card

2023-10-24 20:24 UTC, GuiRuchell requested changes
deixei uns comentarios

2023-10-25 00:08 UTC, GuiRuchell approved these changes

2023-10-25 00:08 UTC, merged